cmake_minimum_required(VERSION 3.28)

get_filename_component(source "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
if(DEFINED CASE)
  set(ENV{PATH} "${TEST_DIR}/usr/bin:$ENV{PATH}")
  set(ENV{LLVM_ROOT} "")
  if(CASE STREQUAL "override")
    set(ENV{LLVM_ROOT} "${TEST_DIR}/custom llvm")
    set(expected "$ENV{LLVM_ROOT}")
  else()
    set(expected "${TEST_DIR}/usr/lib/llvm-19")
  endif()
  if(CASE STREQUAL "cached-search")
    set(WFCLI_CLANG_IN_PATH "${TEST_DIR}/missing/clang" CACHE FILEPATH "")
  elseif(CASE STREQUAL "changed-compiler")
    set(CMAKE_CXX_COMPILER "${TEST_DIR}/old/bin/clang++")
  elseif(CASE STREQUAL "changed-version")
    set(WFCLI_CONFIGURED_LLVM "${expected};clang version 18" CACHE INTERNAL "")
  endif()

  include("${source}/cmake/gui-toolchain.cmake")
  if(NOT WFCLI_LLVM_ROOT STREQUAL expected)
    message(FATAL_ERROR "Wrong LLVM prefix: ${WFCLI_LLVM_ROOT}, expected ${expected}")
  endif()
  if(NOT "$ENV{LLVM_ROOT}" STREQUAL expected)
    message(FATAL_ERROR "LLVM prefix not passed to child processes")
  endif()
  string(FIND "$ENV{LD_LIBRARY_PATH}" "${expected}/lib:" runtime_position)
  if(NOT runtime_position EQUAL 0)
    message(FATAL_ERROR "LLVM runtime directory not passed to child processes")
  endif()
  include("${source}/cmake/gui-toolchain.cmake")
  foreach(baseline "" x86-64 x86-64-v2 native)
    set(ENV{WFCLI_CPU_BASELINE} "${baseline}")
    include("${source}/cmake/vcpkg-triplets/x64-linux-llvm-libcxx.cmake")
    if(NOT VCPKG_C_FLAGS STREQUAL "-march=x86-64-v2"
       OR NOT VCPKG_CXX_FLAGS STREQUAL "-march=x86-64-v2")
      message(FATAL_ERROR "Shared dependency ABI changed with ambient CPU flags")
    endif()
  endforeach()
  return()
endif()

if(NOT DEFINED TEST_DIR)
  message(FATAL_ERROR "TEST_DIR is required")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}/usr/bin")
foreach(prefix "${TEST_DIR}/usr/lib/llvm-19" "${TEST_DIR}/custom llvm")
  file(MAKE_DIRECTORY "${prefix}/bin" "${prefix}/include/c++/v1" "${prefix}/lib")
  foreach(tool clang clang++ llvm-ar llvm-ranlib)
    file(WRITE "${prefix}/bin/${tool}" "#!/bin/sh\nprintf 'clang version 19.1.7\\n'\n")
    file(CHMOD "${prefix}/bin/${tool}"
      PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
  endforeach()
  foreach(runtime c++ c++abi unwind)
    file(WRITE "${prefix}/lib/lib${runtime}.so" "")
  endforeach()
endforeach()
file(CREATE_LINK "../lib/llvm-19/bin/clang" "${TEST_DIR}/usr/bin/clang" SYMBOLIC)

foreach(case path override cached-search changed-compiler changed-version)
  execute_process(COMMAND "${CMAKE_COMMAND}" "-DCASE=${case}" "-DTEST_DIR=${TEST_DIR}"
    -P "${CMAKE_CURRENT_LIST_FILE}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(case MATCHES "^changed-")
    if(result EQUAL 0 OR NOT error MATCHES "make gui-reconfigure")
      message(FATAL_ERROR "${case}: stale toolchain was not rejected: ${output}${error}")
    endif()
  elseif(NOT result EQUAL 0)
    message(FATAL_ERROR "${case}: ${output}${error}")
  endif()
endforeach()

find_program(make NAMES make REQUIRED)
execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=LLVM_ROOT
  "PATH=${TEST_DIR}/usr/bin:/usr/bin:/bin" "${make}" --no-print-directory
  -C "${source}" "--eval=print-llvm: ; @printf '%s' \"$(LLVM_ROOT)\"" print-llvm
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
if(NOT result EQUAL 0 OR NOT output STREQUAL "${TEST_DIR}/usr/lib/llvm-19")
  message(FATAL_ERROR "Make did not select Clang from PATH: ${output}${error}")
endif()

message(STATUS "GUI toolchain checks passed")
